name: Publish radashi@beta

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  publish-beta:
    name: Publish Beta
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: '22.x'
          cache: pnpm
      - run: pnpm install
      - run: pnpm build

      - name: Install script dependencies
        run: |
          pnpm install -C scripts/versions

      - name: Publish
        env:
          GIT_CLIFF_PAT: ${{ secrets.GIT_CLIFF_PAT }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          NIGHTLY_DEPLOY_KEY: ${{ secrets.NIGHTLY_DEPLOY_KEY }}
          RJS_TOKEN: ${{ secrets.RJS_TOKEN }}
        run: |
          ./scripts/versions/node_modules/.bin/tsx ./scripts/versions/ci-publish.ts --tag beta
